services:
  mqtt-broker:
    build: .
    container_name: microgrid-mqtt-broker
    hostname: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    environment:
      - TZ=UTC
    volumes:
      - ./config:/config
      - ./data:/data
      - ./log:/log
      - ./secrets:/secrets